Sprite DERLA0, 60, 25
{
    Patch "Patches/Weapons/RocketLauncher/RocketLauncher_Pickup.png", 0, 0
    Offset 30, 25
}

Sprite DRLFA0, 78, 75
{
    Patch "Patches/Weapons/RocketLauncher/RocketLauncher_FireA.png", 0, 0
    Offset -121, -93
}

Sprite DRLFB0, 81, 79
{
    Patch "Patches/Weapons/RocketLauncher/RocketLauncher_FireB.png", 0, 0
    Offset -120, -89
}

Sprite DRLFC0, 85, 82
{
    Patch "Patches/Weapons/RocketLauncher/RocketLauncher_FireC.png", 0, 0
    Offset -118, -86
}

Sprite DRLFD0, 85, 81
{
    Patch "Patches/Weapons/RocketLauncher/RocketLauncher_FireD.png", 0, 0
    Offset -118, -87
}

Sprite DRLFE0, 85, 82
{
    Patch "Patches/Weapons/RocketLauncher/RocketLauncher_FireE.png", 0, 0
    Offset -118, -86
}

Sprite DRLGA0, 78, 72
{
    Patch "Patches/Weapons/RocketLauncher/RocketLauncher_Idle.png", 0, 0
    Offset -121, -96
}

Sprite DRLGB0, 85, 65
{
    Patch "Patches/Weapons/RocketLauncher/RocketLauncher_FireF.png", 0, 0
    Offset -118, -103
}

Sprite DRLGC0, 81, 70
{
    Patch "Patches/Weapons/RocketLauncher/RocketLauncher_FireG.png", 0, 0
    Offset -120, -98
}
