#include "zscript/ricardoluis0/include.zs"

/*
#include "zscript/ricardoluis0/weapons/shield/shieldbit.zs"
#include "zscript/ricardoluis0/My_Globals.zs"
#include "zscript/ricardoluis0/playerclasses/myplayer.zs"
#include "zscript/ricardoluis0/playerclasses/mymarine.zs"
#include "zscript/ricardoluis0/weapons/myweapon.zs"
#include "zscript/ricardoluis0/thingspawner.zs"
#include "zscript/ricardoluis0/weapons/assaultrifle.zs"
#include "zscript/ricardoluis0/weapons/pump.zs"
#include "zscript/ricardoluis0/weapons/pistol.zs"
#include "zscript/ricardoluis0/weapons/mcrossbow.zs"
#include "zscript/ricardoluis0/weapons/remotec4.zs"
#include "zscript/ricardoluis0/weapons/resurrector.zs"
#include "zscript/ricardoluis0/weapons/rocketlauncher.zs"
#include "zscript/ricardoluis0/weapons/gatlingrocket.zs"
#include "zscript/ricardoluis0/weapons/guidedrocket.zs"
#include "zscript/ricardoluis0/weapons/heavygatlinggun.zs"
#include "zscript/ricardoluis0/weapons/spawners/slotxspawners.zs"
#include "zscript/ricardoluis0/enemies/myenemy.zs"
#include "zscript/ricardoluis0/enemies/newzombieman.zs"
#include "zscript/ricardoluis0/enemies/newshotgunguy.zs"
#include "zscript/ricardoluis0/enemies/newimp.zs"
*/