#include "zscript/ricardoluis0/testmod/enemies/MD_Spawner.zs"
#include "zscript/ricardoluis0/testmod/enemies/enemybase.zs"
#include "zscript/ricardoluis0/testmod/enemies/zombieman.zs"
#include "zscript/ricardoluis0/testmod/enemies/shotgunguy.zs"
//#include "zscript/ricardoluis0/testmod/enemies/chaingunguy"
#include "zscript/ricardoluis0/testmod/enemies/imp.zs"