#include "zscript/ricardoluis0/testmod/enemies/MD_Spawner.zs"
#include "zscript/ricardoluis0/testmod/enemies/myenemy.zs"
#include "zscript/ricardoluis0/testmod/enemies/newzombieman.zs"
#include "zscript/ricardoluis0/testmod/enemies/newshotgunguy.zs"
#include "zscript/ricardoluis0/testmod/enemies/newimp.zs"